#
# Test file for stereo camera calibration from tag board including IMU
#
#
targets:
  - name: "apriltag board"
    type: "apriltag_board"
    detector: "umich"
    family: "tf36h11"
    starting_tag_id: 0
    tag_size: 0.07
    rows: 3
    distance_rows: 0.087
    columns: 4
    distance_columns: 0.087

imus:
  - name: "imu_0"
    topic: "/vectornav/imu_uncompensated"
    gyroscope_noise_density: 1e-6 # in rad/sec *  1/sqrt(Hz)
    accelerometer_noise_density: 1e-6 # in m/sec^2 *  1/sqrt(Hz)
    gyroscope_random_walk: 1e-4 # gyro bias random walk in rad/sec^2 *  1/sqrt(Hz)
    accelerometer_random_walk: 1e-4 # accel bias in m/sec^3 *  1/sqrt(Hz)
    gyro_bias_prior:
      x: 0.0
      y: 0.0
      z: 0.0
      sigma: 0.1 # gives strength of gyro bias prior in rad/s
    accelerometer_bias_prior:
      x: 0.0
      y: 0.0
      z: 0.0
      sigma: 0.1 # gives strength of accelerometer bias prior in m/s^2
cameras:
  - name: camera_0
    image_topic: /cam_sync/cam_0/image_raw
    detections_topic: /cam_sync/cam_0/image_raw/detections
    pixel_noise: 1.0
    intrinsics:
      fx: 840.28
      fy: 838.01
      cx: 746.80
      cy: 550.76
    intrinsics_sigma:
      fx: 0.06
      fy: 0.06
      cx: 0.04
      cy: 0.02
    distortion_model:
      type: equidistant
      coefficients:
        - -0.0121
        - -0.0075
        - 0.0017
        - 0.0007
      coefficient_mask: [1, 1, 1, 1]
      coefficient_sigma:
        - 0.000002
        - 0.000027
        - 0.000058
        - 0.000014
  - name: camera_1
    image_topic: /cam_sync/cam_1/image_raw
    detections_topic: /cam_sync/cam_1/image_raw/detections
    pixel_noise: 1.0
    intrinsics:
      fx: 840.36
      fy: 837.82
      cx: 728.53
      cy: 586.51
    intrinsics_sigma:
      fx: 0.05
      fy: 0.06
      cx: 0.04
      cy: 0.02
    distortion_model:
      type: equidistant
      coefficients:
        - -0.0160
        - 0.0088
        - -0.0183
        - 0.0084
      coefficient_mask: [1, 1, 1, 1]
      coefficient_sigma:
        - 0.000001
        - 0.000015
        - 0.000025
        - 0.000005
